name: Compile C Code

on:
  push:
    branches:
      - main
      
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Mingw-w64
        run: sudo apt-get install mingw-w64
        
      - name: Compile C Code for Windows 64-bit
        run: x86_64-w64-mingw32-gcc -Wall -Wextra -g -o 01_C/00_compile_me.c -o code.exe
        
      - name: Upload the EXE file to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic commit
