name: Compile C++ Code

on:
  workflow_dispatch:

jobs:
  get-latest-mingw:
    name: MinGW download
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Wget MinGW and unzip it. Also unzip SDL2.
        run: |
          wget -O libs/mingw.zip https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0-16.0.6-11.0.0-ucrt-r1/winlibs-i686-posix-dwarf-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.0-r1.7z
          7z x libs/mingw.zip -olibs/mingw
          ls -la libs/
        
  mingw64-gcc:
    name: MinGW GCC

    #runs-on: windows-2019
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:          
        
      - name: "Setup"
        run: |
          pwd
          gcc --version
          

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Compile C Code for Linux
        #run: g++ -Wall -Wextra -g 04_cc/00_compile_me.cc -o c_code

#      - name: Install Mingw-w64
 #       run: sudo apt-get install mingw-w64
      
  #    - name: Extract SDL2
   #     run: tar -xf ./libs/SDL2-devel-2.28.1-mingw.tar.gz
      
      #- name: Install SDL2
        #run: sudo apt-get install libsdl2-dev
      
      # This finds the location of /usr/include/SDL2
      #- name: Find the SDL 2 libraries
      #  run: sudo find / -type d -name SDL2

      - name: Extract SDL2 for Windows
        run: 7z x libs/SDL2-devel-2.28.2-mingw.zip -olibs/SDL2

      - name: Compile Code for everyone
        run: |
          x86_64-w64-mingw32-g++ -static -Wall -Wextra -g -o main.exe -I./SDL2-2.28.1/x86_64-w64-mingw32/include 04_cc/00_compile_me.cc -L./SDL2-2.28.1/x86_64-w64-mingw32/lib -lSDL2
          gcc main 00_compile_me.cc -g -lSDL2
        #run: x86_64-w64-mingw32-g++ -static -Wall -Wextra -g -o main.exe 04_cc/00_compile_me.cc

      - name: Upload files to repo
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic commit
