name: Compile C++ Code for Linux

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
jobs:

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile C Code for Linux
        run: time g++ -Wall -Wextra -g 04_cc/00_compile_me.cc -o c_code

      - name: Upload files to repo
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic commit
