name: Compile C++ Code

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Compile C Code for Linux
        #run: g++ -Wall -Wextra -g 04_cc/00_compile_me.cc -o c_code

      - name: Install Mingw-w64
        run: sudo apt-get install mingw-w64
      
      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev
      
      # This finds the location of /usr/include/SDL2
      - name: Find the SDL 2 libraries
        run: sudo find / -type d -name SDL2

      - name: List the content of /usr/include/SDL2
        run: sudo ls /usr/include/SDL2

      - name: Compile Code for everyone
        run: |
          x86_64-w64-mingw32-g++ -static -Wall -Wextra -g -o main.exe -I/usr/include/SDL2 04_cc/00_compile_me.cc -L/usr/lib/SDL2 -lSDL2
          gcc main 00_compile_me.cc -g -lSDL2
        #run: x86_64-w64-mingw32-g++ -static -Wall -Wextra -g -o main.exe 04_cc/00_compile_me.cc

      - name: Upload files to repo
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic commit
