name: Compile C Code

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile C Code for Linux
        run: gcc -Wall -Wextra -g 01_C/00_compile_me.c -o c_code

      - name: Run C Code for Linux
        run: ./c_code > output.txt

      - name: Install Mingw-w64
        run: sudo apt-get install mingw-w64

      - name: Compile C Code for Windows 64-bit
        run: x86_64-w64-mingw32-gcc -Wall -Wextra -g -o c_code.exe 01_C/00_compile_me.c

      - name: Upload files to repo
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic commit
