name: Run Python code

on:
  push:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install required libraries
        run: pip install -r ./02_python/requirements.txt

      - name: Run Python code
        run: python ./02_python/code.py > python_output.txt

      - name: Upload files to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic commit
