name: Run Python code

on:
  push:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install textstat
        run: pip install asciimatics

      - name: Run Python
        run: python ./02_python/feyn_it_right.py > python_output.txt

      - name: Upload the files to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic commit
